# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: greenlight
    volumes:
      - ./tools/postgresql/data:/var/lib/postgresql/data

